// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id)
VALUES ($1)
RETURNING user_id, balance, created_at
`

type CreateWalletRow struct {
	UserID    int32
	Balance   pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateWallet(ctx context.Context, userID int32) (CreateWalletRow, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i CreateWalletRow
	err := row.Scan(&i.UserID, &i.Balance, &i.CreatedAt)
	return i, err
}
